export const dashboardCopy = {
  en: {
    common: {
      notSpecified: "Not specified",
      slashSeparator: " / ",
    },
    header: {
      navLabel: "Dashboard",
      nav: {
        overview: "Overview",
        focus: "Focus",
        habits: "Habits",
        fitness: "Fitness",
      },
      userMenu: {
        accountLabel: "Account",
        login: "Log in",
        signedInAs: "Signed in as",
        fallbackUser: "Coreflow user",
        signOut: "Sign out",
      },
    },
    dashboard: {
      badge: "Overview",
      title: "Keep your systems moving.",
      description:
        "Your first Coreflow slice starts with habits, while study sessions and workouts are already represented in the dashboard structure for the next implementation steps.",
      manageHabits: "Manage habits",
      metrics: {
        habitsToday: {
          label: "Habits completed today",
          detail: "Daily completions are powered by habit log entries for the current day.",
        },
        completionRate: {
          label: "Daily completion rate",
          detail: "A quick signal for whether your day is keeping pace with your targets.",
        },
        longestStreak: {
          label: "Longest active streak",
          detail: "Computed from consecutive completion dates so streaks survive refreshes and deploys.",
        },
        modulesInProgress: {
          label: "Modules in progress",
          detail: "Study sessions and workouts are scaffolded in the schema and dashboard roadmap.",
        },
      },
      habitMomentum: {
        title: "Habit momentum",
        description: "The habits module is fully wired into the dashboard metrics.",
        emptyTitle: "No habits yet",
        emptyDescription: "Create your first habit to start generating daily progress and streak data.",
        emptyAction: "Create a habit",
        doneToday: "Done today",
        pending: "Pending",
        habitStats: (currentStreak: number, completionsThisWeek: number) =>
          `${currentStreak} day streak \u00b7 ${completionsThisWeek} completions this week`,
      },
      nextModules: {
        title: "Next modules",
        description: "Scaffolded space for the rest of the MVP roadmap.",
        studySessions: {
          title: "Study sessions",
          description: "Timer, history, and duration analytics can plug into the same authenticated app shell.",
        },
        workoutTracking: {
          title: "Workout tracking",
          description: "Plans, exercises, and workout logs already have table definitions in the initial schema.",
        },
        stripePlans: {
          title: "Stripe plans",
          description: "The subscription table and env placeholders are ready for free-vs-pro gating next.",
        },
      },
    },
    habits: {
      badge: "Habits",
      title: "Build consistency with simple daily loops.",
      description:
        "This module handles the full MVP flow: create habits, mark today as complete, track streaks, and keep the dashboard updated automatically.",
      summary: {
        active: "Active habits",
        doneToday: "Done today",
        bestStreak: "Best streak",
      },
      form: {
        title: "Create habit",
        description: "Start with the smallest reliable version of the routine you want to keep.",
        name: "Name",
        namePlaceholder: "Read for 20 minutes",
        descriptionLabel: "Description",
        descriptionPlaceholder: "Optional note or why it matters",
        targetDays: "Target days per week",
        pending: "Creating habit...",
        submit: "Save habit",
      },
      list: {
        title: "Habit list",
        description: "Daily completions are stored separately, so your streak math stays resilient.",
        emptyTitle: "Your habits will show up here",
        emptyDescription:
          "Once you create a habit, you can mark it complete for today, watch the streak grow, and see the metrics land on the dashboard.",
        doneToday: "Done today",
        needsCheckIn: "Needs check-in",
        undoToday: "Undo today",
        markComplete: "Mark complete",
        deleteLabel: (name: string) => `Delete ${name}`,
        habitStats: (currentStreak: number, completionsThisWeek: number, frequencyPerWeek: number) => [
          `${currentStreak} day streak`,
          `${completionsThisWeek} completions this week`,
          `${frequencyPerWeek} target days / week`,
        ],
      },
    },
    fitness: {
      badge: "Fitness",
      title: "Build a workout from real exercises.",
      description: "Search the catalog, inspect the movement, then assemble a focused plan with sets, reps, rest, and notes.",
      initialLoadError: "Fitness data could not be loaded yet. Check the backend connection, then search again.",
      fallbackError: "Something went wrong.",
      planCreated: "Workout plan created.",
      exerciseAdded: "Exercise added to the workout.",
      createPlanFirst: "Create a workout plan and select an exercise first.",
      defaults: {
        searchQuery: "squat",
        planName: "Strength foundation",
        planDescription: "A focused plan built from the exercise catalog.",
      },
      metrics: {
        results: "Results",
        plans: "Plans",
        inPlan: "In plan",
      },
      catalog: {
        title: "Exercise catalog",
        description: "Results come from Coreflow backend endpoints, not the external provider directly.",
        searchAria: "Search exercises",
        searchPlaceholder: "chest press, squat, shoulder press",
        searchButton: "Search",
        noResults: "No exercises yet. Try a broader search like squat or press.",
        equipment: (value: string) => `Equipment: ${value}`,
      },
      inspector: {
        emptyTitle: "Select an exercise",
        emptyDescription: "Pick a catalog result to inspect media, details, and workout settings.",
        selected: "Selected",
        loadingDetails: "Loading details",
        formNotes: "Form notes",
        sets: "Sets",
        reps: "Reps",
        restSeconds: "Rest sec",
        notes: "Notes",
        notesPlaceholder: "Tempo, range, warm-up, or coaching cue",
        addToWorkout: "Add to workout",
      },
      builder: {
        title: "Workout builder",
        description: "Create a plan, then add exercises from the catalog.",
        planName: "Plan name",
        planDescription: "Description",
        savePlan: "Save workout plan",
        noWorkout: "No workout yet",
        noWorkoutDescription: "Create a plan to start collecting selected exercises.",
        emptyPlan: "Exercises you add will appear here in order with sets, reps, rest, and notes.",
        sets: "Sets",
        reps: "Reps",
        rest: "Rest",
      },
    },
  },
  "pt-BR": {
    common: {
      notSpecified: "Nao informado",
      slashSeparator: " / ",
    },
    header: {
      navLabel: "Dashboard",
      nav: {
        overview: "Visao geral",
        focus: "Foco",
        habits: "Habitos",
        fitness: "Treino",
      },
      userMenu: {
        accountLabel: "Conta",
        login: "Entrar",
        signedInAs: "Conectado como",
        fallbackUser: "Usuario Coreflow",
        signOut: "Sair",
      },
    },
    dashboard: {
      badge: "Visao geral",
      title: "Mantenha seus sistemas em movimento.",
      description:
        "A primeira parte do Coreflow comeca pelos habitos, enquanto sessoes de estudo e treinos ja aparecem na estrutura do dashboard para os proximos passos.",
      manageHabits: "Gerenciar habitos",
      metrics: {
        habitsToday: {
          label: "Habitos concluidos hoje",
          detail: "Conclusoes diarias usam registros de habito criados para o dia atual.",
        },
        completionRate: {
          label: "Taxa diaria de conclusao",
          detail: "Um sinal rapido para saber se o dia esta acompanhando suas metas.",
        },
        longestStreak: {
          label: "Maior sequencia ativa",
          detail: "Calculada por datas consecutivas para manter as sequencias apos recarregamentos e deploys.",
        },
        modulesInProgress: {
          label: "Modulos em progresso",
          detail: "Sessoes de estudo e treinos ja estao preparados no schema e no roadmap do dashboard.",
        },
      },
      habitMomentum: {
        title: "Ritmo dos habitos",
        description: "O modulo de habitos ja alimenta as metricas do dashboard.",
        emptyTitle: "Nenhum habito ainda",
        emptyDescription: "Crie seu primeiro habito para gerar progresso diario e dados de sequencia.",
        emptyAction: "Criar habito",
        doneToday: "Feito hoje",
        pending: "Pendente",
        habitStats: (currentStreak: number, completionsThisWeek: number) =>
          `${currentStreak} dias de sequencia \u00b7 ${completionsThisWeek} conclusoes nesta semana`,
      },
      nextModules: {
        title: "Proximos modulos",
        description: "Espaco preparado para o restante do roadmap MVP.",
        studySessions: {
          title: "Sessoes de estudo",
          description: "Timer, historico e analise de duracao podem entrar no mesmo app autenticado.",
        },
        workoutTracking: {
          title: "Registro de treino",
          description: "Planos, exercicios e logs de treino ja tem definicoes de tabela no schema inicial.",
        },
        stripePlans: {
          title: "Planos Stripe",
          description: "A tabela de assinatura e os env placeholders estao prontos para diferenciar free e pro.",
        },
      },
    },
    habits: {
      badge: "Habitos",
      title: "Construa consistencia com ciclos diarios simples.",
      description:
        "Este modulo cobre o fluxo MVP completo: criar habitos, marcar hoje como concluido, acompanhar sequencias e atualizar o dashboard automaticamente.",
      summary: {
        active: "Habitos ativos",
        doneToday: "Feitos hoje",
        bestStreak: "Melhor sequencia",
      },
      form: {
        title: "Criar habito",
        description: "Comece pela menor versao confiavel da rotina que voce quer manter.",
        name: "Nome",
        namePlaceholder: "Ler por 20 minutos",
        descriptionLabel: "Descricao",
        descriptionPlaceholder: "Nota opcional ou motivo importante",
        targetDays: "Dias alvo por semana",
        pending: "Criando habito...",
        submit: "Salvar habito",
      },
      list: {
        title: "Lista de habitos",
        description: "Conclusoes diarias ficam separadas para manter o calculo de sequencia resiliente.",
        emptyTitle: "Seus habitos vao aparecer aqui",
        emptyDescription:
          "Depois de criar um habito, voce pode marcar o dia como concluido, acompanhar a sequencia e ver as metricas no dashboard.",
        doneToday: "Feito hoje",
        needsCheckIn: "Precisa check-in",
        undoToday: "Desfazer hoje",
        markComplete: "Marcar concluido",
        deleteLabel: (name: string) => `Excluir ${name}`,
        habitStats: (currentStreak: number, completionsThisWeek: number, frequencyPerWeek: number) => [
          `${currentStreak} dias de sequencia`,
          `${completionsThisWeek} conclusoes nesta semana`,
          `${frequencyPerWeek} dias alvo / semana`,
        ],
      },
    },
    fitness: {
      badge: "Treino",
      title: "Monte um treino com exercicios reais.",
      description: "Pesquise o catalogo, veja o movimento e monte um plano focado com series, repeticoes, descanso e notas.",
      initialLoadError: "Os dados de treino ainda nao puderam ser carregados. Verifique a conexao com o backend e tente pesquisar novamente.",
      fallbackError: "Algo deu errado.",
      planCreated: "Plano de treino criado.",
      exerciseAdded: "Exercicio adicionado ao treino.",
      createPlanFirst: "Crie um plano de treino e selecione um exercicio primeiro.",
      defaults: {
        searchQuery: "squat",
        planName: "Base de forca",
        planDescription: "Um plano focado criado a partir do catalogo de exercicios.",
      },
      metrics: {
        results: "Resultados",
        plans: "Planos",
        inPlan: "No plano",
      },
      catalog: {
        title: "Catalogo de exercicios",
        description: "Os resultados vem dos endpoints backend do Coreflow, nao do provedor externo diretamente.",
        searchAria: "Pesquisar exercicios",
        searchPlaceholder: "chest press, squat, shoulder press",
        searchButton: "Pesquisar",
        noResults: "Nenhum exercicio ainda. Tente uma busca mais ampla como squat ou press.",
        equipment: (value: string) => `Equipamento: ${value}`,
      },
      inspector: {
        emptyTitle: "Selecione um exercicio",
        emptyDescription: "Escolha um resultado do catalogo para ver midia, detalhes e ajustes do treino.",
        selected: "Selecionado",
        loadingDetails: "Carregando detalhes",
        formNotes: "Notas de execucao",
        sets: "Series",
        reps: "Reps",
        restSeconds: "Descanso",
        notes: "Notas",
        notesPlaceholder: "Tempo, amplitude, aquecimento ou dica tecnica",
        addToWorkout: "Adicionar ao treino",
      },
      builder: {
        title: "Montador de treino",
        description: "Crie um plano e adicione exercicios do catalogo.",
        planName: "Nome do plano",
        planDescription: "Descricao",
        savePlan: "Salvar plano de treino",
        noWorkout: "Nenhum treino ainda",
        noWorkoutDescription: "Crie um plano para comecar a reunir exercicios selecionados.",
        emptyPlan: "Os exercicios adicionados aparecem aqui em ordem com series, reps, descanso e notas.",
        sets: "Series",
        reps: "Reps",
        rest: "Descanso",
      },
    },
  },
};
