export const focusCopy = {
  en: {
    badge: "Focus",
    title: "Plan the work, then enter the session.",
    description:
      "A structured study system for choosing what matters, protecting time, and closing the loop when the work is done.",
    actions: {
      create: "Create session",
      start: "Start",
      select: "Select",
      complete: "Mark complete",
      pause: "Pause",
      resume: "Resume",
      reset: "Reset",
      save: "Save session",
      saving: "Saving...",
    },
    fallbackError: "Study session could not be saved.",
    overview: {
      totalFocus: "Focus time",
      completed: "Completed",
      activePending: "Active / pending",
      completionRate: "Completion rate",
      minutes: (value: number) => `${value} min`,
      ratio: (active: number, pending: number) => `${active} / ${pending}`,
    },
    planner: {
      title: "Plan next study block",
      description: "Capture the next unit of work before starting the timer.",
      titleLabel: "Title",
      titlePlaceholder: "Review cellular respiration",
      descriptionLabel: "Description",
      descriptionPlaceholder: "Optional scope, source, or success criteria",
      subjectLabel: "Subject",
      subjectPlaceholder: "Biology",
      estimatedLabel: "Estimated minutes",
      startLabel: "Start date",
      dueLabel: "Due date",
      difficultyLabel: "Difficulty",
      importanceLabel: "Importance",
    },
    list: {
      title: "Study sessions",
      description: "Keep the plan small enough to execute and clear enough to resume quickly.",
      emptyTitle: "No sessions match this view",
      emptyDescription: "Adjust filters or create a study block to start building your focus queue.",
      filters: {
        status: "Status",
        difficulty: "Difficulty",
        importance: "Importance",
        all: "All",
      },
      estimated: (minutes: number) => `${minutes} min planned`,
      focusLogged: (minutes: number) => `${minutes} min logged`,
      dateRange: (start: string, due: string) => `${start} to ${due}`,
    },
    pomodoro: {
      title: "Pomodoro execution",
      description: "Tie the timer to a selected session and close the loop when the work is finished.",
      noSession: "Select a study session to bind the timer.",
      selected: "Selected session",
      phase: {
        focus: "Focus",
        short_break: "Short break",
        long_break: "Long break",
        complete: "Cycle complete",
      },
      settings: {
        focusMinutes: "Focus",
        shortBreakMinutes: "Short break",
        longBreakMinutes: "Long break",
        cycles: "Cycles",
      },
      cycle: (current: number, total: number) => `Cycle ${current} of ${total}`,
    },
    levels: {
      low: "Low",
      medium: "Medium",
      high: "High",
    },
    status: {
      pending: "Pending",
      in_progress: "In progress",
      completed: "Completed",
    },
    samples: {
      sessions: {
        "session-1": {
          description: "Review the core concepts and write one short recall summary.",
          subject: "Biology",
          title: "Cellular respiration review",
        },
        "session-2": {
          description: "Work through practice problems without checking the answer key first.",
          subject: "Math",
          title: "Integrals practice set",
        },
        "session-3": {
          description: "Annotate the chapter and extract five arguments into notes.",
          subject: "History",
          title: "Cold War chapter notes",
        },
      },
    },
  },
  "pt-BR": {
    badge: "Foco",
    title: "Planeje o estudo, depois entre na sessao.",
    description:
      "Um sistema de estudo estruturado para escolher o que importa, proteger tempo e fechar o ciclo quando o trabalho termina.",
    actions: {
      create: "Criar sessao",
      start: "Iniciar",
      select: "Selecionar",
      complete: "Concluir",
      pause: "Pausar",
      resume: "Retomar",
      reset: "Resetar",
      save: "Salvar sessao",
      saving: "Salvando...",
    },
    fallbackError: "Nao foi possivel salvar a sessao de estudo.",
    overview: {
      totalFocus: "Tempo focado",
      completed: "Concluidas",
      activePending: "Ativas / pendentes",
      completionRate: "Taxa de conclusao",
      minutes: (value: number) => `${value} min`,
      ratio: (active: number, pending: number) => `${active} / ${pending}`,
    },
    planner: {
      title: "Planejar proximo bloco",
      description: "Registre a proxima unidade de estudo antes de iniciar o timer.",
      titleLabel: "Titulo",
      titlePlaceholder: "Revisar respiracao celular",
      descriptionLabel: "Descricao",
      descriptionPlaceholder: "Escopo, fonte ou criterio de sucesso opcional",
      subjectLabel: "Materia",
      subjectPlaceholder: "Biologia",
      estimatedLabel: "Minutos estimados",
      startLabel: "Data inicial",
      dueLabel: "Data limite",
      difficultyLabel: "Dificuldade",
      importanceLabel: "Importancia",
    },
    list: {
      title: "Sessoes de estudo",
      description: "Mantenha o plano pequeno o bastante para executar e claro o bastante para retomar rapido.",
      emptyTitle: "Nenhuma sessao nesta visao",
      emptyDescription: "Ajuste os filtros ou crie um bloco de estudo para montar sua fila de foco.",
      filters: {
        status: "Status",
        difficulty: "Dificuldade",
        importance: "Importancia",
        all: "Todos",
      },
      estimated: (minutes: number) => `${minutes} min planejados`,
      focusLogged: (minutes: number) => `${minutes} min registrados`,
      dateRange: (start: string, due: string) => `${start} ate ${due}`,
    },
    pomodoro: {
      title: "Execucao Pomodoro",
      description: "Conecte o timer a uma sessao selecionada e feche o ciclo quando terminar.",
      noSession: "Selecione uma sessao de estudo para conectar ao timer.",
      selected: "Sessao selecionada",
      phase: {
        focus: "Foco",
        short_break: "Pausa curta",
        long_break: "Pausa longa",
        complete: "Ciclo completo",
      },
      settings: {
        focusMinutes: "Foco",
        shortBreakMinutes: "Pausa curta",
        longBreakMinutes: "Pausa longa",
        cycles: "Ciclos",
      },
      cycle: (current: number, total: number) => `Ciclo ${current} de ${total}`,
    },
    levels: {
      low: "Baixa",
      medium: "Media",
      high: "Alta",
    },
    status: {
      pending: "Pendente",
      in_progress: "Em progresso",
      completed: "Concluida",
    },
    samples: {
      sessions: {
        "session-1": {
          description: "Revise os conceitos principais e escreva um resumo curto de memoria.",
          subject: "Biologia",
          title: "Revisao de respiracao celular",
        },
        "session-2": {
          description: "Resolva exercicios sem consultar o gabarito primeiro.",
          subject: "Matematica",
          title: "Lista de integrais",
        },
        "session-3": {
          description: "Anote o capitulo e extraia cinco argumentos para suas notas.",
          subject: "Historia",
          title: "Notas do capitulo sobre Guerra Fria",
        },
      },
    },
  },
};

export type FocusCopy = (typeof focusCopy)["en"];
