export const focusCopy = {
  en: {
    badge: "Focus",
    title: "Protect the block. Finish the work.",
    description:
      "Choose the target, run the timer, and close the session with a clean record of effort.",
    actions: {
      create: "Create session",
      edit: "Edit",
      start: "Start",
      select: "Select",
      cancel: "Cancel",
      archive: "Archive",
      delete: "Delete",
      complete: "Mark complete",
      pause: "Pause",
      resume: "Resume",
      reset: "Reset",
      saveFocus: "Save focus time",
      savingFocus: "Saving time...",
      useStandalone: "Use free focus",
      save: "Save session",
      saving: "Saving...",
      update: "Update session",
      updating: "Updating...",
      stopEditing: "Cancel edit",
    },
    deleteDialog: {
      cancelLabel: "Keep session",
      confirmLabel: "Delete session",
      description:
        "This permanently removes the study session and any focus runs linked to it. Archive the session instead if you may need the record later.",
      title: "Delete study session?",
    },
    fallbackError: "Study session could not be saved.",
    notices: {
      sessionCreated: "Study session created. You can start it as soon as you are ready to focus.",
      sessionUpdated: "Study session updated.",
      sessionCompleted: "Study session completed. It is now part of your focus history.",
      sessionCanceled: "Study session canceled. You can plan a cleaner block when you are ready.",
      sessionArchived: "Study session archived. It is out of the active queue now.",
      sessionDeleted: "Study session deleted.",
      focusSaved: "Focus time saved. The dashboard totals are up to date.",
      focusRunCanceled: "Focus run discarded.",
      editingSession: "Editing session. Adjust the plan, then jump back into execution.",
    },
    overview: {
      totalFocus: "Focus time",
      todayFocus: "Today",
      weekFocus: "This week",
      completed: "Completed",
      activePending: "Active / pending",
      completionRate: "Completion rate",
      minutes: (value: number) => `${value} min`,
      duration: formatDuration,
      ratio: (active: number, pending: number) => `${active} / ${pending}`,
    },
    planner: {
      title: "Plan the next block",
      description: "Define one clear target before the timer starts.",
      editTitle: "Update study block",
      editDescription: "Adjust the plan, dates, or priority without losing saved focus time.",
      titleLabel: "Title",
      titlePlaceholder: "Review cellular respiration",
      descriptionLabel: "Description",
      descriptionPlaceholder: "Optional scope, source, or success criteria",
      subjectLabel: "Subject",
      subjectPlaceholder: "Biology",
      estimatedLabel: "Estimated minutes",
      startLabel: "Start date",
      dueLabel: "Due date",
      difficultyLabel: "Difficulty",
      importanceLabel: "Importance",
    },
    list: {
      title: "Study sessions",
      description: "Keep the plan small enough to execute and clear enough to resume quickly.",
      upcomingTitle: "Upcoming and active",
      completedTitle: "Completed",
      archivedTitle: "Canceled and archived",
      historyTitle: "Focus history",
      historyDescription: "Review completed study blocks and saved focus work.",
      emptyTitle: "Give the timer one clear target",
      emptyDescription: "Plan a single focus block, then start the timer from the same screen.",
      emptyAction: "Plan first block",
      emptyHint: "A useful first block is specific enough to finish in one Pomodoro.",
      historyEmptyTitle: "Your completed focus will collect here",
      historyEmptyDescription: "Finish a study block or save focus time to build a visible record of effort.",
      historyEmptyAction: "Plan a focus block",
      historyEmptyHint: "The first saved run turns Focus from a timer into a progress record.",
      details: "Details",
      filters: {
        status: "Status",
        difficulty: "Difficulty",
        importance: "Importance",
        all: "All",
      },
      estimated: (minutes: number) => `${minutes} min planned`,
      focusLogged: (seconds: number) => `${formatDuration(seconds)} focused`,
      cyclesLogged: (cycles: number) => `${cycles} cycles completed`,
      dateRange: (start: string, due: string) => `${start} to ${due}`,
      completedAt: (value: string) => `Completed ${value}`,
      freeFocus: "Free focus",
      runCount: (count: number) => `${count} runs saved`,
    },
    pomodoro: {
      title: "Execution timer",
      description: "Run a clean focus cycle, linked to a session when the target is known.",
      noSession: "Free focus mode",
      noSessionDescription: "Time will be saved as standalone focus history.",
      selected: "Linked study session",
      active: "Active study session",
      standaloneTotal: (seconds: number) => `${formatDuration(seconds)} saved outside sessions`,
      currentRun: (seconds: number) => `${formatDuration(seconds)} in this run`,
      savedSessionTotal: (seconds: number) => `${formatDuration(seconds)} already saved to this session`,
      cyclesSaved: (cycles: number) => `${cycles} completed cycles saved`,
      status: "Status",
      readyToResume: "Session is active and ready to resume.",
      phase: {
        focus: "Focus",
        short_break: "Short break",
        long_break: "Long break",
        complete: "Cycle complete",
      },
      settings: {
        focusMinutes: "Focus",
        shortBreakMinutes: "Short break",
        longBreakMinutes: "Long break",
        cycles: "Cycles",
      },
      cycle: (current: number, total: number) => `Cycle ${current} of ${total}`,
    },
    levels: {
      low: "Low",
      medium: "Medium",
      high: "High",
    },
    status: {
      pending: "Pending",
      in_progress: "In progress",
      completed: "Completed",
      canceled: "Canceled",
      archived: "Archived",
    },
  },
  "pt-BR": {
    badge: "Foco",
    title: "Proteja o bloco. Conclua o trabalho.",
    description:
      "Escolha o alvo, rode o timer e feche a sessao com um registro limpo de esforco.",
    actions: {
      create: "Criar sessao",
      edit: "Editar",
      start: "Iniciar",
      select: "Selecionar",
      cancel: "Cancelar",
      archive: "Arquivar",
      delete: "Excluir",
      complete: "Concluir",
      pause: "Pausar",
      resume: "Retomar",
      reset: "Resetar",
      saveFocus: "Salvar tempo focado",
      savingFocus: "Salvando tempo...",
      useStandalone: "Usar foco livre",
      save: "Salvar sessao",
      saving: "Salvando...",
      update: "Atualizar sessao",
      updating: "Atualizando...",
      stopEditing: "Cancelar edicao",
    },
    deleteDialog: {
      cancelLabel: "Manter sessao",
      confirmLabel: "Excluir sessao",
      description:
        "Isso remove permanentemente a sessao de estudo e todos os registros de foco vinculados a ela. Arquive a sessao se talvez precisar do registro depois.",
      title: "Excluir sessao de estudo?",
    },
    fallbackError: "Nao foi possivel salvar a sessao de estudo.",
    notices: {
      sessionCreated: "Sessao de estudo criada. Ela ja pode virar seu proximo bloco de foco.",
      sessionUpdated: "Sessao de estudo atualizada.",
      sessionCompleted: "Sessao de estudo concluida. Ela agora faz parte do seu historico de foco.",
      sessionCanceled: "Sessao de estudo cancelada. Voce pode planejar um bloco mais limpo quando quiser.",
      sessionArchived: "Sessao de estudo arquivada. Ela saiu da fila ativa.",
      sessionDeleted: "Sessao de estudo excluida.",
      focusSaved: "Tempo de foco salvo. Os totais do dashboard ja foram atualizados.",
      focusRunCanceled: "Execucao de foco descartada.",
      editingSession: "Editando sessao. Ajuste o plano e volte para a execucao.",
    },
    overview: {
      totalFocus: "Tempo focado",
      todayFocus: "Hoje",
      weekFocus: "Nesta semana",
      completed: "Concluidas",
      activePending: "Ativas / pendentes",
      completionRate: "Taxa de conclusao",
      minutes: (value: number) => `${value} min`,
      duration: formatDuration,
      ratio: (active: number, pending: number) => `${active} / ${pending}`,
    },
    planner: {
      title: "Planejar o proximo bloco",
      description: "Defina um alvo claro antes de iniciar o timer.",
      editTitle: "Atualizar bloco de estudo",
      editDescription: "Ajuste o plano, as datas ou a prioridade sem perder o foco ja salvo.",
      titleLabel: "Titulo",
      titlePlaceholder: "Revisar respiracao celular",
      descriptionLabel: "Descricao",
      descriptionPlaceholder: "Escopo, fonte ou criterio de sucesso opcional",
      subjectLabel: "Materia",
      subjectPlaceholder: "Biologia",
      estimatedLabel: "Minutos estimados",
      startLabel: "Data inicial",
      dueLabel: "Data limite",
      difficultyLabel: "Dificuldade",
      importanceLabel: "Importancia",
    },
    list: {
      title: "Sessoes de estudo",
      description: "Mantenha o plano pequeno o bastante para executar e claro o bastante para retomar rapido.",
      upcomingTitle: "Proximas e ativas",
      completedTitle: "Concluidas",
      archivedTitle: "Canceladas e arquivadas",
      historyTitle: "Historico de foco",
      historyDescription: "Revise blocos de estudo concluidos e foco salvo.",
      emptyTitle: "De ao timer um alvo claro",
      emptyDescription: "Planeje um unico bloco de foco e inicie o timer na mesma tela.",
      emptyAction: "Planejar primeiro bloco",
      emptyHint: "Um bom primeiro bloco e especifico o bastante para terminar em um Pomodoro.",
      historyEmptyTitle: "Seu foco concluido vai se acumular aqui",
      historyEmptyDescription: "Conclua um bloco de estudo ou salve tempo focado para criar um registro visivel de esforco.",
      historyEmptyAction: "Planejar bloco de foco",
      historyEmptyHint: "A primeira execucao salva transforma o timer em registro de progresso.",
      details: "Detalhes",
      filters: {
        status: "Status",
        difficulty: "Dificuldade",
        importance: "Importancia",
        all: "Todos",
      },
      estimated: (minutes: number) => `${minutes} min planejados`,
      focusLogged: (seconds: number) => `${formatDuration(seconds)} focados`,
      cyclesLogged: (cycles: number) => `${cycles} ciclos concluidos`,
      dateRange: (start: string, due: string) => `${start} ate ${due}`,
      completedAt: (value: string) => `Concluido ${value}`,
      freeFocus: "Foco livre",
      runCount: (count: number) => `${count} execucoes salvas`,
    },
    pomodoro: {
      title: "Timer de execucao",
      description: "Rode um ciclo limpo de foco, conectado a uma sessao quando o alvo estiver claro.",
      noSession: "Modo foco livre",
      noSessionDescription: "O tempo sera salvo como historico de foco avulso.",
      selected: "Sessao de estudo conectada",
      active: "Sessao de estudo ativa",
      standaloneTotal: (seconds: number) => `${formatDuration(seconds)} salvos fora de sessoes`,
      currentRun: (seconds: number) => `${formatDuration(seconds)} nesta execucao`,
      savedSessionTotal: (seconds: number) => `${formatDuration(seconds)} ja salvos nesta sessao`,
      cyclesSaved: (cycles: number) => `${cycles} ciclos concluidos salvos`,
      status: "Status",
      readyToResume: "A sessao esta ativa e pronta para retomar.",
      phase: {
        focus: "Foco",
        short_break: "Pausa curta",
        long_break: "Pausa longa",
        complete: "Ciclo completo",
      },
      settings: {
        focusMinutes: "Foco",
        shortBreakMinutes: "Pausa curta",
        longBreakMinutes: "Pausa longa",
        cycles: "Ciclos",
      },
      cycle: (current: number, total: number) => `Ciclo ${current} de ${total}`,
    },
    levels: {
      low: "Baixa",
      medium: "Media",
      high: "Alta",
    },
    status: {
      pending: "Pendente",
      in_progress: "Em progresso",
      completed: "Concluida",
      canceled: "Cancelada",
      archived: "Arquivada",
    },
  },
};

export type FocusCopy = (typeof focusCopy)["en"];

function formatDuration(totalSeconds: number) {
  if (totalSeconds <= 0) {
    return "0m";
  }

  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  if (hours > 0) {
    return seconds > 0 ? `${hours}h ${minutes}m ${seconds}s` : `${hours}h ${minutes}m`;
  }

  if (minutes > 0) {
    return seconds > 0 ? `${minutes}m ${seconds}s` : `${minutes}m`;
  }

  return `${seconds}s`;
}
